Openvpn up/down scripts support
kyl191/ansible-role-openvpn pull request #134
Opened 2021-01-06 12:29 UTC by kohoutovice

Hello,
I added support for openvpn up/down scripts. So if you'd like it you can merge it.

2021-01-08 03:06 UTC, kyl191 commented on templates/server.conf.j2
> +up {{openvpn_base_dir}}/down.sh
Should this be `down`?

2021-01-08 03:10 UTC, kyl191 requested changes
Just a weird thing on the `down/up` in server.conf.j2

2021-03-04 09:18 UTC, kohoutovice commented
Yeah, there was a typo mistake. Sorry for that. Now I've made triple check of my changes and tested it in my local enviroment. 

In addition I added the option for client dis/connect script.

2021-03-07 07:06 UTC, kyl191 commented
lgtm. Centos failures are an upstream Ansible problem: https://github.com/ansible/ansible/pull/73689 

Merging.

2021-03-07 07:06 UTC, merged