Revocation: Also remove client cert
kyl191/ansible-role-openvpn pull request #186
Opened 2022-06-23 11:51 UTC by jbeyerstedt

When re-adding a client with the same name, a new key will be generated because the key file was deleted during revocation. But no new and therefore matching certificate will be generated because that file still exists. The result will be a .ovpn file with mismatching key and cert.

2022-08-25 07:28 UTC, jbeyerstedt commented
Any comments on this?

2022-11-17 15:36 UTC, bandikoot commented
@kyl191 , greetings!

Do you think you can accept this PR?

2024-12-22 16:19 UTC, kyl191 commented
Github isn't letting me rebase/merge the latest changes - could you rebase and repush?

2024-12-22 17:25 UTC, kyl191 requested changes
It seems like Github doesn't like permissions on your forked repo so I can't rebase & merge.

2024-12-26 17:41 UTC, closed without merging

2024-12-26 17:41 UTC, kyl191 commented
Managed to keep the attribution (and addressed ansible-lint warnings) in https://github.com/kyl191/ansible-role-openvpn/pull/210/commits/bc58bfaad74e8bf57e327ba2dbba1bef3394026d.

Considering this closed.