Firewall: Use the right IP subnet
kyl191/ansible-role-openvpn pull request #192
Opened 2022-12-19 11:20 UTC by jbeyerstedt

The firewall rules always use a /24 subnet, even if something else was configured in the "openvpn_server_netmask" parameter. This PR uses some ipaddr filter magic to extract the CIDR prefix length from the two netmask and network variables.

This change was originally proposed in #163, but wasn't merged because of the other changes in that PR.

2023-01-22 12:00 UTC, bandikoot commented
@kyl191, greetings!

I use `/16` subnet for vpn clients. Recently i have spent quite a few hours researching what's wrong with packets routing before I checked out iptables rules & discovered `/24` hardcoded in them.

Is there any chance this PR would be merged? It'd be very helpful.

2024-12-22 16:20 UTC, kyl191 commented
Github isn't letting me rebase/merge the latest changes - could you rebase and repush?

2024-12-22 17:25 UTC, kyl191 requested changes
It seems like Github doesn't like permissions on your forked repo so I can't rebase & merge.

2024-12-28 23:56 UTC, kyl191 commented
Rebased and merged in https://github.com/kyl191/ansible-role-openvpn/pull/218

2024-12-28 23:56 UTC, closed without merging